openapi: 3.0.0
info:
  version: 1.0.0
  title: ReceptDB API
  description: A ReceptDB API útvonal dokumentációja
servers:
  - url: http://localhost:3000
paths:
  /users:
    get:
      description: A felhasználók listája
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A felhasználók listája sikeresen megjött!
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
    post:
      description: Egy felhasználó létrehozása
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: A felhasználó sikeresen létrejött!
          content:
            application/json:
              schema:
                type: json
                items:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{id}:
    get:
      description: Visszaad egy adott felhasználót egy magadott ID-vel
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A felhasználó adat sikeresen megjött
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '404':
          description: Az adott ID-jű felhasználó nem található
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      description: Módosít egy felhasználót
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: A felhasználó sikeresen módosításra került
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: Töröl egy felhasználót
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: A felhasználó sikeresen törlésre került
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - firstName
        - lastName
        - nickName
        - email
        - password
        - countOfRecipes
        - start
      properties:
        firstName:
          type: string
        lastName:
          type: string
        nickName:
          type: string
        email:
          type: string
        password:
          type: string
        countOfRecipes:
          type: number
        start:
          type: date
    Message:
      type: object
      required:
        - email
        - sender
        - subject
        - message
        - status
      properties:
        email:
          type: string
        sender:
          type: string
        subject:
          type: string
        message:
          type: string
        status:
          type: string
    Error:
      type: object
      required:
        - message
        - has_error
      properties:
        message:
          type: string
        has_error:
          type: boolean