version: "3"
services: 
    app:
        container_name: receptBD
        build: 
            dockerfile: Dockerfile
            context: .
        volumes:
            - .:/app
        ports: 
            - "3000:3000"